# Generated by Django 3.0.5 on 2020-04-11 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('file_imd', models.CharField(max_length=100, null=True)),
                ('douban_id', models.CharField(max_length=15, null=True)),
                ('downloas_url', models.CharField(max_length=300)),
                ('cover_img_url', models.CharField(max_length=300, null=True)),
            ],
        ),
    ]
