# Generated by Django 3.0.5 on 2020-04-12 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, null=True)),
                ('author', models.CharField(default='未知', max_length=100)),
                ('file_idm', models.CharField(max_length=100, null=True)),
                ('douban_id', models.CharField(max_length=115, null=True)),
                ('epub_download_url', models.CharField(max_length=300, null=True)),
                ('mobi_download_url', models.CharField(max_length=300, null=True)),
                ('pdf_download_url', models.CharField(max_length=300, null=True)),
                ('azw3_download_url', models.CharField(max_length=300, null=True)),
                ('cover_img_url', models.CharField(default='/static/book/images/null_cover.png', max_length=300, null=True)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
