# Generated by Django 3.0.5 on 2020-04-12 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover_img_url',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
