# Generated by Django 3.0.5 on 2020-04-12 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20200412_1724'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='author',
            new_name='书名',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='name',
            new_name='作者',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='cover_img_url',
            new_name='封面链接',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='brief',
            new_name='简介',
        ),
    ]
