# Generated by Django 3.0.5 on 2020-04-12 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_auto_20200412_2054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='书名',
        ),
        migrations.RemoveField(
            model_name='book',
            name='作者',
        ),
        migrations.RemoveField(
            model_name='book',
            name='封面链接',
        ),
        migrations.RemoveField(
            model_name='book',
            name='简介',
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='作者'),
        ),
        migrations.AddField(
            model_name='book',
            name='azw3_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='book_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='书名'),
        ),
        migrations.AddField(
            model_name='book',
            name='brief',
            field=models.CharField(max_length=1000, null=True, verbose_name='简介'),
        ),
        migrations.AddField(
            model_name='book',
            name='cover_img_url',
            field=models.CharField(max_length=300, null=True, verbose_name='封面链接'),
        ),
        migrations.AddField(
            model_name='book',
            name='epub_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='mobi_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='pdf_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='azw3_download_url',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='douban_id',
            field=models.CharField(blank=True, max_length=115, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='epub_download_url',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='file_idm',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='mobi_download_url',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='pdf_download_url',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
