# Generated by Django 3.0.5 on 2020-04-14 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_auto_20200413_0454'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_img_large_url',
            field=models.CharField(max_length=300, null=True, verbose_name='封面大图链接'),
        ),
        migrations.AlterField(
            model_name='book',
            name='brief',
            field=models.CharField(default='暂无', max_length=1000, null=True, verbose_name='简介'),
        ),
    ]
