# Generated by Django 3.0.5 on 2020-04-15 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_auto_20200414_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='azw3_download_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover_img_large_url',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='封面大图链接'),
        ),
        migrations.AlterField(
            model_name='book',
            name='epub_download_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='file_idm',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='mobi_download_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='pdf_download_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
