# Generated by Django 3.0.5 on 2020-04-15 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_auto_20200415_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='brief',
            field=models.TextField(default='暂无', null=True, verbose_name='简介'),
        ),
    ]
